### Request Login 
POST http://localhost:8000/api/login 
content-type: application/json

{
    "username": "company1@gmail.com", 
    "password": "Jivass@123"
}

###list permission
GET http://localhost:8000/api/permission_list
content-type: application/json
Authorization: Token 7374cbf7c7a8c0b0dac6f8cb4fc89aaa27c675f4

###Get Roles
GET http://localhost:8000/api/newrole/2
content-type: application/json 
Authorization: Token 1e040917545c4dbad255d6d13f12fa1c5db62723


###Add Roles
POST http://localhost:8000/api/newrole/4
content-type: application/json 
Authorization: Token 7374cbf7c7a8c0b0dac6f8cb4fc89aaa27c675f4

{
    "role_name" : "testm",
    "permissions" : [47]
}

###Update Roles
PUT http://localhost:8000/api/updaterole/5
content-type: application/json 
Authorization: Token 1e040917545c4dbad255d6d13f12fa1c5db62723

{
    "role_name" : "Developer",
    "permissions" : [69,48, 47]
}

###Delete Roles
DELETE http://localhost:8000/api/newrole/5
content-type: application/json 
Authorization: Token 1e08c1386d6d2a8f938775f4c71393dc9ff6a90d

###Activate and Deactivate Role
POST http://localhost:8001/api/role/activate
content-type: application/json
Authorization: Token 6bd43b1fe7fb9889d72f9e563560f84b7896bc94

{
    "role_id": 2,
    "activate": true
}
