### Request Login
POST http://localhost:8000/api/login 
content-type: application/json

{
    "username": "hr1@gmail.com",
    "password": "Jivass@123"
}

###get punch
GET http://localhost:8000/api/punch-in
content-type: application/json
Authorization: Token ef3a7ec0ef7fd36430f85cf9eb44f2ea2eea39d3

###punch-in
POST http://localhost:8000/api/punch-in
content-type: application/json
Authorization: Token ef3a7ec0ef7fd36430f85cf9eb44f2ea2eea39d3

###punch-out
POST http://localhost:8000/api/punch-out
content-type: application/json
Authorization: Token ef3a7ec0ef7fd36430f85cf9eb44f2ea2eea39d3