### Request Login
POST http://localhost:8000/api/login 
content-type: application/json

{
    "username": "hr1@gmail.com",
    "password": "Jivass@123"
}

###get punch
GET http://localhost:8000/api/punch-in
content-type: application/json
Authorization: Token 627c58988afc54f5c5b502c3794b47a4e9bca79f

###punch-in
POST http://localhost:8000/api/punch-in
content-type: application/json
Authorization: Token 627c58988afc54f5c5b502c3794b47a4e9bca79f

###punch-out
POST http://localhost:8000/api/punch-out
content-type: application/json
Authorization: Token 627c58988afc54f5c5b502c3794b47a4e9bca79f