### Request Login 
POST http://localhost:8000/api/login 
content-type: application/json

{
    "username": "admin1@jivass.com", 
    "password": "Jivass@123"
}

### Request Create Admin 
POST http://localhost:8000/api/admin
content-type: application/json 

{   
    "company": "Jivass Technolgies",
    "email": "admin1@jivass.com", 
    "first_name": "admin", 
    "last_name": "a",
    "password" : "Jivass@123"
}

### Request Create user 
POST http://localhost:8000/api/user?user_id=9
content-type: application/json 
Authorization: Token 80ff28c7245a776e716dbc067acfd1d56af561bd

{
    "email": "hr@gmail.com", 
    "first_name": "hr", 
    "last_name": "hr", 
    "phone_number": "11238547", 
    "role_id" : 3,
    "password" : "Jivass@123"
}

### Get All Roles
GET  http://localhost:8000/api/role/10
content-type: application/json 