### Request Login 
POST http://localhost:8000/api/login 
content-type: application/json

{
    "username": "admin1@jivass.com", 
    "password": "Jivass@123"
}

### Request get Admin 
GET http://localhost:8000/api/admin
content-type: application/json 
Authorization: Token 6a3e78bc93e58363f046b014b48d06dcd067edc9

### Request delete Admin
DELETE  http://localhost:8000/api/admin/30
content-type: application/json 
Authorization: Token ce2938f7e48c91d836c1862955c5b858dc1d460b

### Request Create Admin 
POST http://localhost:8000/api/admin
content-type: application/json 
Authorization: Token 36e6c900bd5e3a880a3ed584cebbf4748a7eede4

{   
    "company": "Jivass111",
    "email": "aaa@gmail.com"
}

### Request Get user 
GET http://localhost:8000/api/user?user_id=52
content-type: application/json 
Authorization: Token 1aabd52f4ff511ec9122543438450405e8c6b5be

### Request Create user 
POST http://localhost:8000/api/user?user_id=39
content-type: application/json 
Authorization: Token 92b0cf798948fa9c47f27a33238f2d291f860ffa

{
    "email": "hr@gmail.com", 
    "first_name": "hr", 
    "last_name": "hr", 
    "phone_number": "11238547", 
    "role_id" : 3
}

### Get All Roles
GET  http://localhost:8000/api/role/39
content-type: application/json 

### Request Logout
GET http://localhost:8000/api/logout
content-type: application/json
Authorization: Token ace6e002fb7a8fee9816b6ab57e5fee9cc675ee7


### Request Reset/forgot password request
POST http://localhost:8000/api/resetpassword/request
content-type: application/json

{
    "email": "arunsingh@jivass.com"
}


### Request set new password
POST http://localhost:8000/api/resetpassword
content-type: application/json

{
    "token": "d5b870bf480711ef83c4d46a6a1e4800",
    "password": "Test@1234"
}

### Request check is token is valid
POST http://localhost:8000/api/resetpassword/istokenvalid
content-type: application/json

{
    "token": "09b0f3388d2d11ef91d133633c138b67"
}


###test