# Generated by Django 5.1.1 on 2024-10-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compnay',
            new_name='Company',
        ),
    ]
