# Generated by Django 5.1.1 on 2024-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchinout',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punchinout',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
