# Generated by Django 5.1.1 on 2025-01-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_leavetype_reqstatus_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('create_company', ''), ('view_company', ''), ('delete_company', ''), ('create_user', ''), ('edit_user', ''), ('activate_user', ''), ('view_users', ''), ('view_calendar', ''), ('edit_calendar', ''), ('add_role', ''), ('edit_role', ''), ('activate_role', ''), ('punch_in', ''), ('request_leave', ''), ('approve_leave', ''))},
        ),
    ]
