# Generated by Django 5.1.1 on 2024-11-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calendarevent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='user',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='company',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
    ]
