# Generated by Django 5.1.1 on 2024-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_calendarevent_user_calendarevent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
