# Generated by Django 5.1.1 on 2024-11-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_calendarevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='type',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
