# Generated by Django 5.1.1 on 2024-11-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_calendarevent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_filepath',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_filetype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
