# Generated by Django 5.1.1 on 2024-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_profile_picture_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
