# Generated by Django 5.1.1 on 2025-01-28 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='api.companybranch'),
            preserve_default=False,
        ),
    ]
