# Generated by Django 5.1.1 on 2025-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
