# Generated by Django 5.1.1 on 2024-11-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('create_company', ''), ('view_company', ''), ('delete_company', ''), ('create_user', ''), ('edit_user', ''), ('activate_user', ''), ('view_users', ''), ('view_calendar', ''), ('edit_calendar', ''), ('add_role', ''), ('edit_role', ''))},
        ),
    ]
