# Generated by Django 5.1.1 on 2025-01-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('reporting_manager', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('branch_location', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('work_shift', models.CharField(blank=True, max_length=50, null=True)),
                ('user_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], max_length=50)),
                ('associated_projects', models.TextField(blank=True, null=True)),
                ('role_validity_start', models.DateField(blank=True, null=True)),
                ('role_validity_end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=10)),
                ('residential_address', models.TextField()),
                ('nationality', models.CharField(max_length=25)),
                ('identity_proof_type', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_proof_number', models.CharField(blank=True, max_length=25, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('educational_qualifications', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('certifications_skills', models.TextField(blank=True, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
