# Generated by Django 5.1.1 on 2024-12-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customgroup'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='group',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='custom_group', to='auth.group'),
            preserve_default=False,
        ),
    ]
