# Generated by Django 5.1.1 on 2024-12-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customgroup_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={},
        ),
    ]
