# Generated by Django 5.1.1 on 2024-12-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customgroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='group',
        ),
    ]
