# Generated by Django 5.1.1 on 2024-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_customgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_groups',
            field=models.ManyToManyField(related_name='users', to='api.customgroup'),
        ),
    ]
