# Generated by Django 5.1.1 on 2024-12-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_custom_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_groups',
        ),
    ]
